[project]
name = "game-ai"
version = "0.1.0"
description = "todo"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "pickledb>=1.3.2",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = ["pytest>=9.0.1", "ruff>=0.14.5", "ty>=0.0.1a26"]
