[project]
name = "game-ai"
version = "0.1.0"
description = "todo"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = ["arcade>=3.3.2"]

[dependency-groups]
dev = ["pytest>=8.4.2", "ruff>=0.13.0", "ty>=0.0.1a20"]
